FROM node:18-alpine

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

RUN npm ci --only=production

COPY src src

EXPOSE 3060
CMD ["npm", "run", "prod"]
