version: "2"

services:
  sails-styloProd:
    restart: always
    build: .
    links:
      - mongodb-styloProd
      - redis-styloProd
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=stylo.ecrituresnumeriques.ca
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stylo.ecrituresnumeriques.ca
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
  mongodb-styloProd:
    restart: always
    image: mongo:latest
    container_name: "mongodb-stylo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./dataProd/db:/dataProd/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  redis-styloProd:
    restart: always
    image: redis
networks:
  default:
    external:
      name: root_default
