version: '2.4'

services:
  mongodb:
    image: mongo:4.2
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  graphql:
    build: ./graphql/
    image: ghcr.io/ecrituresnumeriques/stylo-graphql
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./stylo.env
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_SERVER_PORT=27017
    ports:
      - 3030:3030

  export:
    build: ./export/
    image: ghcr.io/ecrituresnumeriques/stylo-export
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ./stylo.env
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_SERVER_PORT=27017
    ports:
      - 3060:3060

  front:
    build:
      context: ./front
      dockerfile: dockerfile
    image: ghcr.io/ecrituresnumeriques/stylo-front
    env_file:
      - ./stylo.env
    ports:
      - 3000:3000
    depends_on:
      - graphql
