version: "2"

services:
  sails-stylo:
    restart: always
    build: .
    links:
      - mongodb-stylo
      - redis-stylo
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=stylo.14159.ninja
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stylo.14159.ninja
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
  mongodb-stylo:
    restart: always
    image: mongo:latest
    container_name: "mongodb-stylo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  redis-stylo:
    restart: always
    image: redis
networks:
  default:
    external:
      name: root_default
