version: '2.1'

services:
  mongodb-stylo:
    image: mongo:4.2
    container_name: "mongodb-stylo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
    healthcheck:
      test: ["CMD", "mongo", "--eval", "\"db.adminCommand('ping')\""]
      interval: 30s
      timeout: 5s
    ports:
      - 127.0.0.1:27017:27017

  graphql-stylo:
    build:
      context: ./graphql/
      labels:
        - org.opencontainers.image.source=https://github.com/EcrituresNumeriques/stylo
    image: "ghcr.io/ecrituresnumeriques/stylo-graphql:${TAG:-master}"
    container_name: "graphql-stylo"
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - ./stylo.env
    environment:
      - MONGO_SERVER=mongodb-stylo
      - MONGO_SERVER_PORT=27017
    ports:
      - 127.0.0.1:3030:3030

  export-stylo:
    build:
      context: ./export/
      labels:
        - org.opencontainers.image.source=https://github.com/EcrituresNumeriques/stylo
    container_name: "export-stylo"
    image: "ghcr.io/ecrituresnumeriques/stylo-export:${TAG:-master}"
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - ./stylo.env
    environment:
      - MONGO_SERVER=mongodb-stylo
      - MONGO_SERVER_PORT=27017
    ports:
      - 127.0.0.1:3060:3060

  front-stylo:
    build:
      context: ./front
      dockerfile: dockerfile
      labels:
        - org.opencontainers.image.source=https://github.com/EcrituresNumeriques/stylo
      args:
        - SNOWPACK_MATOMO_URL
        - SNOWPACK_MATOMO_SITE_ID
    image: "ghcr.io/ecrituresnumeriques/stylo-front:${TAG:-master}"
    container_name: "front-stylo"
    env_file:
      - ./stylo.env
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      - graphql-stylo

  export-gateway:
    image: "davidbgk/stylo-export:0.0.10"
    env_file:
      - stylo.env
    environment:
      - SE_PANDOC_API_BASE_URL=${SE_PANDOC_API_BASE_URL:-http://pandoc-api:8000/latest/}
      - SE_ALLOWED_INSTANCE_DOMAINS=${SE_ALLOWED_INSTANCE_DOMAINS:-localhost:3000,localhost:3030}
    ports:
      - 127.0.0.1:3080:8001

  pandoc-api:
    image: "davidbgk/pandoc-api:0.0.10"
    ports:
      - 127.0.0.1:3090:8000

