version: '2.1'

services:
  mongodb-stylo:
    image: mongo:4.2
    container_name: "mongodb-stylo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
    healthcheck:
      test: ["CMD", "mongo", "--eval", "\"db.adminCommand('ping')\""]
      interval: 30s
      timeout: 5s
  graphql-stylo:
    build: ./graphql/
    container_name: "graphql-stylo"
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - ./stylo.env
    environment:
      - MONGO_SERVER=mongodb-stylo
      - MONGO_SERVER_PORT=27017
    ports:
      - 127.0.0.1:3030:3030
  export-stylo:
    build: ./export/
    container_name: "export-stylo"
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - ./stylo.env
    environment:
      - MONGO_SERVER=mongodb-stylo
      - MONGO_SERVER_PORT=27017
    ports:
      - 127.0.0.1:3060:3060
  front-stylo:
    build:
      context: ./front
      dockerfile: dockerfile
      args:
        - SNOWPACK_MATOMO_URL
        - SNOWPACK_MATOMO_SITE_ID
    container_name: "front-stylo"
    env_file:
      - ./stylo.env
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      - graphql-stylo
  export-gateway:
    image: "davidbgk/stylo-export:0.0.3"
    environment:
      - SE_PANDOC_API_BASE_URL=http://pandoc-api:8000/latest/
    ports:
      - 127.0.0.1:3080:8001
  pandoc-api:
    image: "davidbgk/pandoc-api:0.0.5"
    environment:
      - 'TEXINPUTS=.:/usr/pandoc-api/tmp/:'
    ports:
      - 127.0.0.1:3090:8000

