version: "2"

services:
  sails-stylo-prod:
    restart: always
    build: .
    links:
      - mongodb-stylo-prod:mongodb
      - redis-stylo-prod
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=stylo.ecrituresnumeriques.ca
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stylo.ecrituresnumeriques.ca
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
  mongodb-stylo-prod:
    restart: always
    image: mongo:latest
    container_name: "mongodb-stylo-prod"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /home/backup/MongoStylo/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  redis-stylo-prod:
    restart: always
    image: redis
networks:
  default:
    external:
      name: root_default
