version: '2.1'

services:
  mongodb-stylo:
    image: mongo:latest
    container_name: "mongodb-stylo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5
  graphql-stylo:
    build: ./graphql/
    container_name: "graphql-stylo"
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - ./stylo-backend.env
    environment:
      - MONGO_SERVER=mongodb-stylo
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=stylo
    ports:
      - 3030:3030
  export-stylo:
    build: ./export/
    container_name: "export-stylo"
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - ./stylo-export.env
    environment:
      - MONGO_SERVER=mongodb-stylo
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=stylo
    ports:
      - 3060:3060
  front-stylo:
    build:
      context: ./front
      dockerfile: dockerfile
    container_name: "front-stylo"
    env_file:
      - ./stylo-frontend.env
    ports:
      - 3000:3000
    depends_on:
      - graphql-stylo
