services:
  mongodb-stylo:
    # to keep in sync with ./graphql/jest-mongodb-config.js / README.md
    image: mongo:5
    container_name: 'mongodb-stylo'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
    healthcheck:
      test: ['CMD', 'mongo', '--eval', '"db.adminCommand(''ping'')"']
      interval: 30s
      timeout: 5s
    ports:
      - 127.0.0.1:27017:27017

  graphql-stylo:
    build:
      context: ./graphql/
      labels:
        - org.opencontainers.image.source=https://github.com/EcrituresNumeriques/stylo
    image: 'ghcr.io/ecrituresnumeriques/stylo-graphql:${TAG:-latest}'
    container_name: 'graphql-stylo'
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongodb-stylo:27017/stylo-dev
    ports:
      - 127.0.0.1:3030:3030

  front-stylo:
    build:
      context: ./front
      dockerfile: dockerfile
      labels:
        - org.opencontainers.image.source=https://github.com/EcrituresNumeriques/stylo
      args:
        - SNOWPACK_MATOMO_URL
        - SNOWPACK_MATOMO_SITE_ID
    image: 'ghcr.io/ecrituresnumeriques/stylo-front:${TAG:-latest}'
    container_name: 'front-stylo'
    volumes:
      - ./front/build:/usr/share/nginx/html
    env_file:
      - .env
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      - graphql-stylo

  export-stylo:
    image: 'davidbgk/stylo-export:3.0.1'
    container_name: 'export-stylo'
    env_file:
      - .env
    environment:
      - SE_IMAGES_TIMEOUT=10
      - SE_PANDOC_API_BASE_URL=${SE_PANDOC_API_BASE_URL:-http://pandoc-api:8000/latest/}
      - SE_ALLOWED_INSTANCE_BASE_URLS=${SE_ALLOWED_INSTANCE_BASE_URLS:-http://localhost:3000 http://localhost:3030 http://host.docker.internal:3030}
    ports:
      - 127.0.0.1:3080:8001
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  pandoc-api:
    image: 'davidbgk/pandoc-api:3.0.3'
    container_name: 'pandoc-api'
    ports:
      - 127.0.0.1:3090:8000
