# Reference docs: https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
  base = "front/gatsby"
  publish = "build"
  command = "npm run build"

  [build.environment]
    # System env
    NODE_VERSION = "14"
    NODE_ENV = "development"

    # App env (old)
    GATSBY_EXPORT_ENDPOINT = "https://stylo-dev.huma-num.fr"
    GATSBY_GRAPHQL_ENDPOINT = "https://stylo-dev.huma-num.fr/graphql"
    GATSBY_HUMAN_ID_REGISTER_ENDPOINT = ""
    GATSBY_PROCESS_ENDPOINT = "https://stylo-export.ecrituresnumeriques.ca"
    GATSBY_STYLO_BACKEND_ENDPOINT = "https://stylo-dev.huma-num.fr"

    # App env (new Snowpack)
    SNOWPACK_PUBLIC_EXPORT_ENDPOINT = "https://stylo-dev.huma-num.fr"
    SNOWPACK_PUBLIC_GRAPHQL_ENDPOINT = "https://stylo-dev.huma-num.fr/graphql"
    SNOWPACK_PUBLIC_PROCESS_ENDPOINT = "hhttps://stylo-export.ecrituresnumeriques.ca"
    SNOWPACK_PUBLIC_BACKEND_ENDPOINT = "https://stylo-dev.huma-num.fr"
    SNOWPACK_PUBLIC_HUMAN_ID_REGISTER_ENDPOINT = "https://auth-test.huma-num.fr/register?service=http://stylo-dev.huma-num.fr/authorization-code/callback"
    ENABLE_SOURCEMAPS = "true"

# We retain source maps in "production-like" deploy preview
[context.production.environment]
  NODE_ENV = "production"
  ENABLE_SOURCEMAPS = "true"


[[redirects]]
  from = "/*"
  to = "/index.html"
  force = false
  status = 200
