version: '2.1'

services:
  mongodb-stylo-prod:
    image: mongo:latest
    container_name: "mongodb-stylo-prod"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 5
  graphql-stylo-prod:
    build: ./graphql/
    container_name: "graphql-stylo-prod"
    depends_on:
      mongodb-stylo-prod:
        condition: service_healthy
    environment:
      - MONGO_SERVER=mongodb-stylo-prod
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=stylo
      - HTTPS=true
      - JWT_SECRET_TOKEN=SuperSecureButYouShouldChangeMe
      - JWT_SECRET_SESSION=DidITellYouHowMuchYouShouldChangeMe?
      - JWT_SECRET_SESSION_COOKIE=NoNoNoReallyIInsistYouShouldChangeMe
      - ALLOW_CORS_FRONTEND=https://stylo.huma-num.fr
    ports:
      - 3030:80
  export-stylo-prod:
    build: ./export/
    container_name: "export-stylo-prod"
    depends_on:
      mongodb-stylo-prod:
        condition: service_healthy
    environment:
      - MONGO_SERVER=mongodb-stylo-prod
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=stylo
      - URL_FRONTEND=https://stylo.huma-num.fr
    ports:
      - 3060:80
  front-stylo-prod:
    build:
      context: ./front
      dockerfile: dockerfile
    container_name: "front-stylo-prod"
    environment:
      - URL_EXPORT=stylo.ecrituresnumeriques.ca
    ports:
      - 3000:80
    depends_on:
      - graphql-stylo-prod
