version: "2"

services:

#
# Reverse proxy + SSL
#

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "docker-compose/proxy/certs:/etc/nginx/certs:ro"

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "docker-compose/volumes/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "docker-compose/volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen



#
# Stylo
#


  sails-stylo-prod:
    restart: always
    build: .
    links:
      - mongodb-stylo-prod:mongodb
      - redis-stylo-prod
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=stylo.ecrituresnumeriques.ca
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stylo.ecrituresnumeriques.ca
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com

  mongodb-stylo-prod:
    restart: always
    image: mongo:latest
    container_name: "mongodb-stylo-prod"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /home/backup/MongoStylo/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  redis-stylo-prod:
    restart: always
    image: redis