version: '2'

services:
  migrate:
    build: ./migrate/
    container_name: "migrate"
    depends_on:
      - mongodb-stylo
    environment:
      - MONGO_SERVER=mongodb-stylo
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=stylo
networks:
  default:
    external:
      name: root_default