version: '2'

services:
  mongodb-stylo-prod:
    image: mongo:latest
    container_name: "mongodb-stylo-prod"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null 
  mongodb-admin-prod:
    image: mongo-express
    container_name: "mongodb-admin-prod"
    environment:
      - ME_CONFIG_BASICAUTH_PASSWORD=AdminPassword
      - ME_CONFIG_BASICAUTH_USERNAME=Username
    links:
      - mongodb-stylo-prod:mongo
    ports:
      - 3060:8081
  graphql-stylo-prod:
    build: ./graphql/
    container_name: "graphql-stylo-prod"
    depends_on:
      - mongodb-stylo-prod
    environment:
      - MONGO_SERVER=mongodb-stylo-prod
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=stylo
      - HTTPS=true
      - JWT_SECRET_TOKEN=SuperSecureButYouShouldChangeMe
      - JWT_SECRET_SESSION=DidITellYouHowMuchYouShouldChangeMe?
      - JWT_SECRET_SESSION_COOKIE=NoNoNoReallyIInsistYouShouldChangeMe
      - ALLOW_CORS_FRONTEND=https://stylo.huma-num.fr
      - VIRTUAL_HOST=cchum-kvm-stylo.in2p3.fr
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=cchum-kvm-stylo.in2p3.fr
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
  export-stylo-prod:
    build: ./export/
    container_name: "export-stylo-prod"
    depends_on:
      - mongodb-stylo-prod
    environment:
      - MONGO_SERVER=mongodb-stylo-prod
      - MONGO_SERVER_PORT=27017
      - MONGO_SERVER_DB=stylo
      - URL_FRONTEND=https://stylo.huma-num.fr
      - VIRTUAL_HOST=stylo.ecrituresnumeriques.ca
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stylo.ecrituresnumeriques.ca
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
  front-stylo-prod:
    build: 
      context: ./front
      dockerfile: dockerfile
    container_name: "front-stylo-prod"
    environment:
      - URL_EXPORT=stylo.ecrituresnumeriques.ca
      - VIRTUAL_HOST=stylo.huma-num.fr
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=stylo.huma-num.fr
      - LETSENCRYPT_EMAIL=arthur.juchereau@gmail.com
    depends_on:
      - graphql-stylo-prod
      
networks:
  default:
    external:
      name: root_default