sails-stylo:
  build: .
  dockerfile: dockerfile.standalone
  ports:
    - "8080:80"
  links:
    - mongodb-stylo:mongodb
    - redis-stylo:redis-stylo
  environment:
    - NODE_ENV=development
mongodb-stylo:
  image: mongo:latest
  container_name: "mongodb-stylo"
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
  volumes:
    - ./data/db:/data/db
  ports:
    - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet
redis-stylo:
  image: redis
  ports:
    - "6380:6379"
