FROM node:18.14-alpine3.17

# compatibility with OpenSSL 1.1 for passport/openidconnect (humanid.huma-num.fr)
RUN apk add --update --no-cache openssl1.1-compat

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm clean-install

COPY . .

ENV NODE_ENV "production"
EXPOSE 3030

CMD ["npm", "run", "prod"]

