FROM dhi.io/node:24-alpine3.23-dev AS build-stage

ENV NODE_ENV="production"
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm clean-install --omit=dev

FROM dhi.io/node:24-alpine3.23 AS runtime-stage

ENV NODE_ENV="production"
WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/node_modules ./node_modules

COPY package*.json ./
COPY . .

EXPOSE 3030

CMD ["node", "--tls-max-v1.2", "--heapsnapshot-signal=SIGUSR2", "app.js"]

