#import './Credentials.graphql'

fragment basicCorpusFields on Corpus {
  _id
  createdAt
  creator {
    ...extendedPublicUserFields
  }
  description
  metadata
  name
  type
  updatedAt
}

fragment basicWorkspaceFields on Workspace {
  _id
  name
  color
  description
}

query getCorpus(
  $filter: FilterCorpusInput
  $isPersonalWorkspace: Boolean = true
  $workspaceId: ID
  $includeArticles: Boolean = false
  $includeWorkingVersion: Boolean = false
) {
  corpus(filter: $filter) {
    ...basicCorpusFields

    articles @include(if: $includeArticles) {
      article {
        _id
        title

        workingVersion @include(if: $includeWorkingVersion) {
          md
          bib
          yaml(options: { strip_markdown: true })
        }
      }
    }
  }

  workspace(workspaceId: $workspaceId) @skip(if: $isPersonalWorkspace) {
    ...basicWorkspaceFields
  }
}

query getCorpusArticles($filter: FilterCorpusInput) {
  corpus(filter: $filter) {
    articles {
      article {
        _id
        title

        workingVersion {
          metadata
        }
      }
    }
  }
}

query getCorpusPreview(
  $corpusId: ID!
  $isPersonalWorkspace: Boolean = true
  $workspaceId: ID
) {
  sharedCorpus(corpusId: $corpusId) {
    ...basicCorpusFields

    articles {
      article {
        _id
        title

        workingVersion {
          md
          bib
          yaml(options: { strip_markdown: true })
        }
      }
    }
  }

  workspace(workspaceId: $workspaceId) @skip(if: $isPersonalWorkspace) {
    ...basicWorkspaceFields
  }
}

mutation createCorpus($createCorpusInput: CreateCorpusInput!) {
  createCorpus(createCorpusInput: $createCorpusInput) {
    _id
    name
    description
    creator {
      ...extendedPublicUserFields
    }
    createdAt
    updatedAt
    workspace
  }
}

mutation deleteCorpus($corpusId: ID!) {
  deleteCorpus(corpusId: $corpusId) {
    _id
  }
}

mutation updateMetadata($corpusId: ID!, $metadata: JSON!) {
  updateCorpusMetadata(corpusId: $corpusId, metadata: $metadata) {
    _id
  }
}

mutation updateCorpus($corpusId: ID!, $updateCorpusInput: UpdateCorpusInput!) {
  updateCorpus(corpusId: $corpusId, updateCorpusInput: $updateCorpusInput) {
    _id
  }
}

mutation removeArticleFromCorpus($corpusId: ID!, $articleId: ID!) {
  removeCorpusArticle(corpusId: $corpusId, articleId: $articleId) {
    _id
  }
}

mutation addArticleToCorpus($corpusId: ID!, $articleId: ID!) {
  addCorpusArticle(corpusId: $corpusId, articleId: $articleId) {
    _id
  }
}

mutation updateArticlesOrder(
  $corpusId: ID!
  $articlesOrderInput: [ArticleOrder!]!
) {
  updateCorpusArticlesOrder(
    corpusId: $corpusId
    articlesOrderInput: $articlesOrderInput
  ) {
    _id
  }
}

mutation setCorpusArticles($corpusId: ID!, $articleIds: [ID]!) {
  setCorpusArticles(
    setCorpusArticlesInput: { corpusId: $corpusId, articleIds: $articleIds }
  ) {
    _id
  }
}
