query getTags {
  user {
    tags {
      name
      color
      _id
    }
  }
}

mutation deleteTag($tagId: ID!) {
  deleteTag(tagId: $tagId) {
    _id
  }
}

mutation updateTag(
  $tag: ID!
  $color: HexColorCode!
  $name: String!
  $description: String!
) {
  updateTag(tag: $tag, name: $name, description: $description, color: $color) {
    _id
    name
    description
    color
  }
}

mutation createTag(
  $name: String!
  $description: String
  $color: HexColorCode!
) {
  createTag(name: $name, description: $description, color: $color) {
    _id
    name
    description
    color
  }
}
