# build environment
FROM node:14-alpine as build
WORKDIR /app
COPY gatsby/package*.json ./
RUN npm ci --silent
COPY gatsby ./
RUN npm run build

# production environment
FROM nginx:mainline-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
