FROM node:11

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY gatsby/package*.json ./

RUN npm ci --only=production

# Bundle app source
COPY gatsby .

RUN npm run build

EXPOSE 3000
CMD [ "npm", "run", "serve" ]
