FROM nginx:1.29.4-alpine

RUN apk del -r nginx \
  && apk add --no-cache \
      nginx \
      nginx-mod-http-vts \
      nginx-mod-http-brotli \
      nginx-mod-http-cache-purge \
      nginx-mod-http-headers-more

COPY nginx-default.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
