version: '2.1'

services:
  mongodb-stylo:
    image: mongo:5
    container_name: 'mongodb-stylo'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --logpath=/dev/null
    healthcheck:
      test: ['CMD', 'mongo', '--eval', '"db.adminCommand(''ping'')"']
      interval: 30s
      timeout: 5s
    ports:
      - 127.0.0.1:27017:27017

  graphql-stylo:
    image: 'ghcr.io/ecrituresnumeriques/stylo-graphql:{{app_version}}'
    container_name: 'graphql-stylo'
    volumes:
      - ./data/ydata:/data/ydata
      - ./data/yeditingsession:/data/yeditingsession
    depends_on:
      mongodb-stylo:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongodb-stylo:27017/{{mongo_server_db}}
      - COLLABORATION_PERSISTENCE_DATA_DIR=/data/ydata
      - COLLABORATION_EDITING_SESSION_PERSISTENCE_DATA_DIR=/data/yeditingsession
      - COLLABORATION_UPDATE_WORKING_COPY_INTERVAL_MS=3000
    ports:
      - 127.0.0.1:3030:3030

  front-stylo:
    image: 'ghcr.io/ecrituresnumeriques/stylo-front:{{app_version}}'
    container_name: 'front-stylo'
    volumes:
      - ./front-assets:/usr/share/nginx/html
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      - graphql-stylo

  export-stylo:
    image: 'davidbgk/stylo-export:3.0.1'
    container_name: 'export-stylo'
    env_file:
      - .env
    environment:
      - SE_PANDOC_API_BASE_URL=${SE_PANDOC_API_BASE_URL:-http://pandoc-api:8000/latest/}
      - SE_ALLOWED_INSTANCE_BASE_URLS={{ export_allowed_instance_base_urls }}
    ports:
      - 127.0.0.1:3080:8001
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  pandoc-api:
    image: 'davidbgk/pandoc-api:3.0.3'
    container_name: 'pandoc-api'
    ports:
      - 127.0.0.1:3090:8000
