---

- hosts: stylo

  tasks:
    - name: Set application version
      ansible.builtin.set_fact: app_version="{{ app_version | default('latest') }}"

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Create backup directory if it does not exist
      ansible.builtin.file:
        path: "{{ mongo_backup_path }}"
        state: directory
        mode: "0755"

    - name: Copy config files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: "./backup.sh", dest: "~/stylo/backup.sh", mode: '0755' }

    - name: Run backup
      ansible.builtin.command: ~/stylo/backup.sh
      when: ansible_facts['services']['docker-compose-stylo.service']['state'] | default('not-found') == 'running'
