---

- hosts: stylo

  tasks:
    - name: Set application version
      ansible.builtin.set_fact: app_version="{{ app_version | default('latest') }}"

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Print service facts
      ansible.builtin.debug:
        var: ansible_facts.services

    - name: Copy config files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "./backup.sh", dest: "~/stylo/backup.sh" }

    - name: restart systemd service if it exists
      service:
        state: restarted
        name: ntpd.service
      when: ansible_facts['services']['ntpd.service']['status'] | default('not-found') != 'not-found'
