---

- hosts: stylo

  tasks:
    - name: Set application version
      ansible.builtin.set_fact: app_version="{{ app_version | default('latest') }}"

    - name: Install aptitude
      become: yes
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      become: yes
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: yes
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      become: yes
      apt:
        name:
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./{{ item.name }}.conf
        dest: /etc/nginx/sites-enabled/{{ item.name }}.conf
      with_items:
        - { name: "{{ site }}" }
        - { name: "pandoc-api.{{ site }}" }
        - { name: "export.{{ site }}" }
      notify: reload nginx

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./stylo.ecrituresnumeriques.ca.conf
        dest: /etc/nginx/sites-enabled/stylo.ecrituresnumeriques.ca.conf
      when: site == "stylo.huma-num.fr"
      notify: reload nginx

    - name: Copy systemd service file
      become: yes
      copy:
        src: ./docker-compose-stylo.service
        dest: /etc/systemd/system/docker-compose-stylo.service
      notify: start docker-compose-stylo

    - name: Copy Nagios configuration
      become: yes
      copy:
        src: ./{{ env }}-nagios-nrpe-local.cfg
        dest: /etc/nagios/nrpe_local.cfg

    - name: Copy config files
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "./stylo.env", dest: "~/stylo/stylo.env" }
        - { src: "./docker-compose.yaml", dest: "~/stylo/docker-compose.yaml" }

    - name: Pull Docker containers
      ansible.builtin.shell:
        cmd: "/usr/local/bin/docker-compose pull"
        chdir: ~/stylo

    - name: Generate Shared GraphQL Token
      register: graphql_token
      ansible.builtin.shell:
        cmd: "/usr/local/bin/docker-compose run --no-deps --rm graphql-stylo npm run generate-service-token --silent"
        chdir: ~/stylo
      run_once: true
      no_log: true

    - name: Ensure SE_GRAPHQL_TOKEN is set
      ansible.builtin.lineinfile:
        path: ~/stylo/stylo.env
        regexp: '^SE_GRAPHQL_TOKEN='
        line: "SE_GRAPHQL_TOKEN=\"{{ graphql_token.stdout }}\""

    - name: Start containers
      docker_compose:
        project_src: ~/stylo
        build: false
        pull: false
      environment:
        SNOWPACK_MATOMO_URL: "{{ matomo_url }}"
        SNOWPACK_MATOMO_SITE_ID: "{{ matomo_site_id }}"
        SE_ALLOWED_INSTANCE_BASE_URLS: "{{ export_allowed_instance_base_urls }}"

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded
    - name: start docker-compose-stylo
      become: true
      systemd:
        name: docker-compose-stylo
        state: started
        enabled: yes
