---

- hosts: stylo
  tasks:
    - name: Use python3
      become: yes
      alternatives:
        link: /usr/bin/python
        name: python
        path: /usr/bin/python3.6

    - name: Install pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install Python dependencies
      pip:
        name:
          - pip==20.1
          - docker==4.2.0
          - docker-compose==1.25.5

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./{{ site }}.conf
        dest: /etc/nginx/sites-enabled/{{ site }}.conf
      notify: reload nginx

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./stylo.ecrituresnumeriques.ca.conf
        dest: /etc/nginx/sites-enabled/stylo.ecrituresnumeriques.ca.conf
      when: site == "stylo.huma-num.fr"
      notify: reload nginx

    - name: Copy systemd service file
      become: yes
      copy:
        src: ./docker-compose-stylo.service
        dest: /etc/systemd/system/docker-compose-stylo.service
      notify: start docker-compose-stylo

    - name: Checkout and update Stylo
      git:
        repo: 'https://github.com/EcrituresNumeriques/stylo.git'
        dest: ~/stylo
        version: 'master'

    - name: Copy environment config file
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: './stylo.env', dest: '~/stylo/stylo.env' }
        - { src: './stylo.env', dest: '~/stylo/front/gatsby/.env.production' }

    - name: Rebuild and restart Docker containers
      docker_compose:
        project_src: ~/stylo
        build: yes

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded
    - name: start docker-compose-stylo
      become: true
      systemd:
        name: docker-compose-stylo
        state: started
        enabled: yes
