---

- hosts: stylo
  tasks:
    - name: Use python3
      become: yes
      alternatives:
        link: /usr/bin/python
        name: python
        path: /usr/bin/python3.6

    - name: Install pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install Python dependencies
      pip:
        name:
          - pip==20.1
          - docker==4.2.0
          - docker-compose==1.25.5

    - name: Install Python monitoring tools
      become: yes
      pip:
        name:
          - check-docker==2.2.2
        umask: "0022"

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./{{ site }}.conf
        dest: /etc/nginx/sites-enabled/{{ site }}.conf
      notify: reload nginx

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./stylo.ecrituresnumeriques.ca.conf
        dest: /etc/nginx/sites-enabled/stylo.ecrituresnumeriques.ca.conf
      when: site == "stylo.huma-num.fr"
      notify: reload nginx

    - name: Copy systemd service file
      become: yes
      copy:
        src: ./docker-compose-stylo.service
        dest: /etc/systemd/system/docker-compose-stylo.service
      notify: start docker-compose-stylo

    - name: Copy Nagios configuration
      become: yes
      copy:
        src: ./{{ env }}-nagios-nrpe-local.cfg
        dest: /etc/nagios/nrpe_local.cfg

    - name: Copy environment config file
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: './stylo.env', dest: '~/stylo/stylo.env' }
        - { src: './stylo.env', dest: '~/stylo/front/gatsby/.env.production' }

    - name: Copy docker-compose
      become: yes
      copy:
        src: ../docker-compose.yaml
        dest: ~/stylo/docker-compose.yaml

    - name: Alias docker images
      shell: |
        docker pull ghcr.io/ecrituresnumeriques/stylo-{{ item }}:{{ app_version }}
        docker tag --force ghcr.io/ecrituresnumeriques/stylo-{{ item }}:{{ app_version }} ghcr.io/ecrituresnumeriques/stylo-{{ item }}:latest
      loop:
        - graphql
        - export
        - front

    - name: Restart Docker containers
      docker_compose:
        project_src: ~/stylo

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded
    - name: start docker-compose-stylo
      become: true
      systemd:
        name: docker-compose-stylo
        state: started
        enabled: yes
