---

- hosts: stylo
  tasks:
    - name: Use python3
      alternatives:
        name: python
        path: /usr/bin/python3

    - name: Install pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install Python dependencies
      pip:
        name:
          - pip==20.1
          - docker==4.2.0
          - docker-compose==1.25.5

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./{{ item }}
        dest: /etc/nginx/sites-enabled/{{ item }}
      loop:
        - stylo-dev.huma-num.fr.conf
        # - stylo.huma-num.fr.conf
      notify: reload nginx

    - name: Checkout and update Stylo
      git:
        repo: 'https://github.com/EcrituresNumeriques/stylo.git'
        dest: ~/stylo
        version: 'issue-151-auth-user-pass'

    - name: Copy environment config file to front
      copy:
        src: ~/stylo/stylo.env
        dest: ~/stylo/front/gatsby/.env.production
        remote_src: yes

    - name: Rebuild and restart Docker containers
      docker_compose:
        project_src: ~/stylo
        build: yes

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded