---

- hosts: stylo

  tasks:
    - name: Set application version
      ansible.builtin.set_fact: app_version="{{ app_version | default('latest') }}"

    - name: Install aptitude
      become: yes
      ansible.builtin.apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      become: yes
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: yes
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      become: yes
      ansible.builtin.apt:
        name:
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true

    - name: Update NGINX settings
      become: yes
      ansible.builtin.copy:
        src: ./{{ item.name }}.conf
        dest: /etc/nginx/sites-enabled/{{ item.name }}.conf
      with_items:
        - { name: "{{ site }}" }
        - { name: "pandoc-api.{{ site }}" }
        - { name: "export.{{ site }}" }
      notify: reload nginx

    - name: Update NGINX settings
      become: yes
      ansible.builtin.copy:
        src: ./stylo.ecrituresnumeriques.ca.conf
        dest: /etc/nginx/sites-enabled/stylo.ecrituresnumeriques.ca.conf
      when: site == "stylo.huma-num.fr"
      notify: reload nginx

    - name: Prune Docker images
      become: yes
      ansible.builtin.shell:
        cmd: "docker image prune -af"
      run_once: true

    - name: Prune Docker system
      become: yes
      ansible.builtin.shell:
        cmd: "docker system prune -af"
      run_once: true

    - name: Copy systemd service file
      become: yes
      ansible.builtin.copy:
        src: ./docker-compose-stylo.service
        dest: /etc/systemd/system/docker-compose-stylo.service
      notify: start docker-compose-stylo

    - name: Copy Nagios configuration
      become: yes
      ansible.builtin.copy:
        src: ./{{ env }}-nagios-nrpe-local.cfg
        dest: /etc/nagios/nrpe_local.cfg

    - name: Copy config files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "./.env", dest: "~/stylo/.env" }
        - { src: "./docker-compose.yaml", dest: "~/stylo/docker-compose.yaml" }

    - name: Pull Docker containers
      ansible.builtin.shell:
        cmd: "docker compose pull"
        chdir: ~/stylo

    - name: Generate Shared GraphQL Token
      register: graphql_token
      ansible.builtin.shell:
        cmd: "docker compose run --no-deps --rm graphql-stylo npm run generate-service-token --silent"
        chdir: ~/stylo
      run_once: true
      no_log: true

    - set_fact:
        "se_graphql_token": "{{ graphql_token.stdout }}"

    - name: Update config files
      ansible.builtin.template:
        src: "./.env"
        dest: "~/stylo/.env"

    - name: Copy frontend assets files
      ansible.posix.synchronize:
        src: "{{ assets_path }}"
        dest: "~/stylo/front-assets/"
        delete: true

    - name: Restart containers
      become: true
      ansible.builtin.systemd:
        name: docker-compose-stylo
        state: restarted
        daemon_reload: true
      environment:
        NODE_OPTIONS: "{{ node_options_flag }}"

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded
    - name: start docker-compose-stylo
      become: true
      ansible.builtin.systemd:
        name: docker-compose-stylo
        state: started
        enabled: yes
