---

- hosts: stylo

  environment:
    # Used to set the correct docker-compose images tags
    TAG: "{{ app_version | default('latest') }}"

  tasks:
    - name: Use python3
      become: yes
      alternatives:
        link: /usr/bin/python
        name: python
        path: /usr/bin/python3.6

    - name: Install pip
      become: yes
      apt:
        name: python3-pip
        state: present

    - name: Install Python dependencies
      pip:
        name:
          - pip==20.1
          - docker==4.2.0
          - docker-compose==1.25.5

    - name: Install Python monitoring tools
      become: yes
      pip:
        name:
          - check-docker==2.2.2
        umask: "0022"

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./{{ item.name }}.conf
        dest: /etc/nginx/sites-enabled/{{ item.name }}.conf
      with_items:
        - { name: "{{ site }}" }
        - { name: "pandoc-api.{{ site }}" }
        - { name: "export.{{ site }}" }
      notify: reload nginx

    - name: Update NGINX settings
      become: yes
      copy:
        src: ./stylo.ecrituresnumeriques.ca.conf
        dest: /etc/nginx/sites-enabled/stylo.ecrituresnumeriques.ca.conf
      when: site == "stylo.huma-num.fr"
      notify: reload nginx

    - name: Copy systemd service file
      become: yes
      copy:
        src: ./docker-compose-stylo.service
        dest: /etc/systemd/system/docker-compose-stylo.service
      notify: start docker-compose-stylo

    - name: Copy Nagios configuration
      become: yes
      copy:
        src: ./{{ env }}-nagios-nrpe-local.cfg
        dest: /etc/nagios/nrpe_local.cfg

    - name: Copy docker-compose.yml
      copy:
        src: "../docker-compose.yml"
        dest: "~/stylo/docker-compose.yml"

    - name: Pull Docker containers
      ansible.builtin.shell:
        cmd: "docker-compose pull"
        chdir: ~/stylo

    - name: Generate Shared GraphQL Token
      register: graphql_token
      ansible.builtin.shell:
        cmd: "docker-compose run --no-deps --rm graphql-stylo npm run generate-service-token --silent"
        chdir: ~/stylo
      run_once: true
      no_log: true

    - name: Register Shared GraphQL Token as a dynamic Ansible Fact
      set_fact:
        shared_graphql_token: "{{ graphql_token.stdout }}"
      run_once: true

    - name: Interpolate environment config file
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "./stylo.env", dest: "~/stylo/stylo.env" }

    - name: Start containers
      docker_compose:
        project_src: ~/stylo
        build: false
        pull: false
      environment:
        SNOWPACK_MATOMO_URL: "{{ matomo_url }}"
        SNOWPACK_MATOMO_SITE_ID: "{{ matomo_site_id }}"
        SE_ALLOWED_INSTANCE_BASE_URLS: "{{ export_allowed_instance_base_urls }}"

  handlers:
    - name: reload nginx
      become: true
      service:
        name: nginx
        state: reloaded
    - name: start docker-compose-stylo
      become: true
      systemd:
        name: docker-compose-stylo
        state: started
        enabled: yes
