name: Ansible backup prod

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release version
        required: true
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  backup:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://stylo.huma-num.fr

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12 (w/ cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '**/deploy-requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install -r .github/workflows/deploy-requirements.txt

      - name: Set Ansible config secrets
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD_PROD }}" > infrastructure/.ansible-vault-password

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Run backup playbook
        working-directory: ./infrastructure
        run: |
          ansible-playbook -v -i inventories/prod \
            --extra-vars "@vault-prod.yml" \
            --extra-vars "app_version=${{ inputs.release-version }}" \
            --private-key ~/.ssh/id_ed25519 \
            --vault-password-file ./.ansible-vault-password \
            backup-playbook.yml
