name: Docker images

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker images
      run: |
        cp stylo-example.env stylo.env
        docker-compose build
        docker-compose run front-stylo npm test
