name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*' 

jobs:
  build-front:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci --prefix front/gatsby
    - name: Build front
      run: npm run build --prefix front/gatsby
    - name: Test
      run: npm t --prefix front/gatsby
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker images
      run: |
        cp stylo-example.env stylo.env
        docker-compose build
