name: Build and deploy Docker images

on:
  push:
    branches:
    - master
    paths:
    - 'graphql/**'
    - 'front/**'
    - 'export/**'
    - '.github/workflows/docker.yml'
    - 'docker-compose.yaml'
    - 'stylo-example.env'
  pull_request:
    paths:
    - 'graphql/**'
    - 'front/**'
    - 'export/**'
    - '.github/workflows/docker.yml'
    - 'docker-compose.yaml'
    - 'stylo-example.env'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cp stylo-example.env stylo.env
    - run: docker-compose build
