name: Node `export` application

on:
  push:
    branches:
    - master
    paths:
    - 'export/**'
    - '.github/workflows/node*.yml'
  pull_request:
    paths:
    - 'export/**'
    - '.github/workflows/node*.yml'

jobs:
  build:
    uses: EcrituresNumeriques/stylo/.github/workflows/node.yml@master
    with:
      app-dir: export
