name: Publish Docker image

on:
  push:
    tags:
    - 'v*'
    branches:
    - master

jobs:
  # Github Container Registry must have been enabled first
  # https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/enabling-improved-container-support#enabling-github-container-registry-for-your-organization-account
  docker-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # via https://github.community/t/how-to-get-just-the-tag-name/16241/10
    - name: Compute tag name
      id: branch
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}

    - name: Build images
      run: |
        cp stylo-example.env stylo.env
        docker-compose build
        echo ${{ secrets.GCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

    - name: Publish images
      run: |
        docker tag ghcr.io/ecrituresnumeriques/stylo-graphql ghcr.io/ecrituresnumeriques/stylo-graphql:${PUBLISH_TAG}
        docker tag ghcr.io/ecrituresnumeriques/stylo-front ghcr.io/ecrituresnumeriques/stylo-front:${PUBLISH_TAG}
        docker tag ghcr.io/ecrituresnumeriques/stylo-export ghcr.io/ecrituresnumeriques/stylo-export:${PUBLISH_TAG}
        
        docker push ghcr.io/ecrituresnumeriques/stylo-graphql:${PUBLISH_TAG}
        docker push ghcr.io/ecrituresnumeriques/stylo-front:${PUBLISH_TAG}
        docker push ghcr.io/ecrituresnumeriques/stylo-export:${PUBLISH_TAG}
      env:
        PUBLISH_TAG: ${{ steps.branch.outputs.SOURCE_NAME }}